import apiClient from './apiClient';

export interface Office {
  id: number;
  name: string | null;
  parentId: number | null;
  externalId: string | null;
  openingDate: string | null;
  address: string | null;
  phone: string | null;
  email: string | null;
  notes: string | null;
  managerId: number | null;
  active: boolean;
  /** The head office; every other office is a branch. */
  defaultOffice: boolean;
  /** Generated by the server on creation, e.g. BCK453-324-61. Null only for offices awaiting backfill. */
  officeCode: string | null;
  parentName: string | null;
  stateId: number | null;
  stateName: string | null;
  lgaId: number | null;
  lgaName: string | null;
  cityId: number | null;
  cityName: string | null;
  zoneId: number | null;
  zoneName: string | null;
  staffCount: number;
  createdAt: string | null;
  createdById: number | null;
  createdByName: string | null;
}

export interface SaveOfficeInput {
  name: string;
  parentId?: number | null;
  externalId?: string | null;
  openingDate?: string | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  notes?: string | null;
  managerId?: number | null;
  defaultOffice?: boolean;
  // Required by the API on create and edit.
  stateId?: number | null;
  lgaId?: number | null;
  cityId?: number | null;
  zoneId?: number | null;
}

export interface OfficeInUse {
  activeClientCount: number;
  openLoanCount: number;
}

export const officesApi = {
  async list(): Promise<Office[]> {
    const response = await apiClient.get<Office[]>('/offices');
    return response.data;
  },

  async get(id: number): Promise<Office> {
    const response = await apiClient.get<Office>(`/offices/${id}`);
    return response.data;
  },

  async create(input: SaveOfficeInput): Promise<Office> {
    const response = await apiClient.post<Office>('/offices', input);
    return response.data;
  },

  async update(id: number, input: SaveOfficeInput): Promise<Office> {
    const response = await apiClient.put<Office>(`/offices/${id}`, input);
    return response.data;
  },

  async activate(id: number): Promise<Office> {
    const response = await apiClient.post<Office>(`/offices/${id}/activate`);
    return response.data;
  },

  /** Throws an ApiError with status 409 and responseData shaped as OfficeInUse if not confirmed and the office is in use. */
  async deactivate(id: number, confirm = false): Promise<Office> {
    const response = await apiClient.post<Office>(`/offices/${id}/deactivate?confirm=${confirm}`);
    return response.data;
  },
};
